apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perses
  namespace: argocd
  labels:
    fieldstate.nz/source: helm
    fieldstate.nz/class: catalogue
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: saas-fabric-catalogue

  sources:
    - repoURL: https://perses.github.io/helm-charts
      chart: perses
      targetRevision: 0.23.2
      helm:
        releaseName: perses
        ignoreMissingValueFiles: true
        valueFiles:
          - $platform/applications/catalogue/perses/values.yaml
          - $platform/environments/PLACEHOLDER/config/perses.yaml
    - repoURL: https://github.com/FieldstateNZ/saas-fabric-platform.git
      targetRevision: PLACEHOLDER
      ref: platform

  destination:
    server: https://kubernetes.default.svc
    namespace: catalogue

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        fieldstate.nz/system: saas-fabric
        fieldstate.nz/layer: platform
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
