apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-secret-store.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: secret-store
      app.kubernetes.io/part-of: external-secrets
      fieldstate.nz/system: saas-fabric
      fieldstate.nz/layer: platform
