apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-system

resources:
  - gatewayclass.yaml
  - gateway.yaml
  - operator-edge.yaml
  - operator-scheme.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: platform-gateway
      fieldstate.nz/system: saas-fabric
      fieldstate.nz/layer: platform
