apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd.yaml
  - openbao.yaml
  - saas-fabric-control-plane.yaml
  - control-plane-routes.yaml
  - keycloak-routes.yaml

labels:
  - includeSelectors: false
    pairs:
      fieldstate.nz/system: saas-fabric
      fieldstate.nz/layer: platform
      fieldstate.nz/plane: operator
